language: php

php:
  - 7.3
  - 7.4

install:
  - composer install --no-interaction

stages:
  - analyze
  - test

jobs:
  include:
    - stage: analyze
      name: "Static analysis"
      script: composer run analyze
    - name: "Code style"
      script: composer run check

script:
  - composer run test
