language: php

php:
  - 7.3
  - 7.4

before_install:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - composer run analyze
  - composer run check
