language: php

php:
  - 7.4
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  - composer validate

install:
  - composer install --no-interaction

stages:
  - analyze
  - test

jobs:
  include:
    - stage: analyze
      name: "Static analysis"
      script: composer run analyze
    - name: "Code style"
      script: composer run check

script:
  - composer run test
